<?php
class Querys{

  function update_items($DB,$data,$id,$category){
        $sql=sprintf(
          "UPDATE items
          SET
            edit_date='%s',
            name='%s',
            type_id=%d,
            catchcopy='%s',
            detail='%s',
            price_b_1=%d,
            price_b_2=%d,
            price_t_1=%d,
            price_t_2=%d,
            tantou=%d,
            voice_s='%s',
            voice_l='%s',
            address='%s',
            traffic='%s',
            g_area_b=%01.2f,
            g_area_t=%01.2f,
            g_tubo_b=%01.2f,
            g_tubo_t=%01.2f,
            b_area_b=%01.2f,
            b_area_t=%01.2f,
            b_tubo_b=%01.2f,
            b_tubo_t=%01.2f,
            per_area_b=%01.2f,
            per_area_t=%01.2f,
            balcony_b=%01.2f,
            balcony_t=%01.2f,
            scale='%s',
            layout='%s',
            howold='%s',
            build_date='%s',
            land_usage='%s',
            land_type='%s',
            coverage=%d,
            bulk_ratio=%d,
            adm_cost=%d,
            fix_cost=%d,
            man_name='%s',
            bikou='%s',
            r_title_1='%s',
            r_comment_1='%s',
            r_title_2='%s',
            r_comment_2='%s',
            r_title_3='%s',
            r_comment_3='%s',
            is_new=%d,
            is_near_sea=%d,
            is_view_sea=%d,
            is_top=%d,
            visible=%d,
            item_detail='%s',
            category=%d,
            is_sold=%d,
            next_date='%s'
          WHERE
            id=%d",
          mysql_escape_string(date("Y-m-d")),
          mysql_escape_string($data["name"]),
          $data["type_id"],
          mysql_escape_string($data["catchcopy"]),
          mysql_escape_string($data["detail"]),
          $data["price_b_1"],
          $data["price_b_2"],
          $data["price_t_1"],
          $data["price_t_2"],
          $data["tantou"],
          mysql_escape_string($data["voice_s"]),
          mysql_escape_string($data["voice_l"]),
          mysql_escape_string($data["address"]),
          mysql_escape_string($data["traffic"]),
          $data["g_area_b"],
          $data["g_area_t"],
          $data["g_tubo_b"],
          $data["g_tubo_t"],
          $data["b_area_b"],
          $data["b_area_t"],
          $data["b_tubo_b"],
          $data["b_tubo_t"],
          $data["per_area_b"],
          $data["per_area_t"],
          $data["balcony_b"],
          $data["balcony_t"],
          mysql_escape_string($data["scale"]),
          mysql_escape_string($data["layout"]),
          mysql_escape_string($data["howold"]),
          mysql_escape_string($data["build_date"]),
          mysql_escape_string($data["land_usage"]),
          mysql_escape_string($data["land_type"]),
          $data["coverage"],
          $data["bulk_ratio"],
          $data["adm_cost"],
          $data["fix_cost"],
          mysql_escape_string($data["man_name"]),
          mysql_escape_string($data["bikou"]),
          mysql_escape_string($data["r_title_1"]),
          mysql_escape_string($data["r_comment_1"]),
          mysql_escape_string($data["r_title_2"]),
          mysql_escape_string($data["r_comment_2"]),
          mysql_escape_string($data["r_title_3"]),
          mysql_escape_string($data["r_comment_3"]),
          $data["is_new"],
          $data["is_near_sea"],
          $data["is_view_sea"],
          $data["is_top"],
          $data["visible"],
          mysql_escape_string($data["item_detail"]),
          $category,
          $data["is_sold"],
          sprintf(
            "%04d-%02d-%02d",
            $data["next_year"],
            $data["next_month"],
            $data["next_day"]
          ),
          $id
        );
//echo nl2br($sql);
        $DB->execute($sql) or die("cannot update.".nl2br($sql));
        $DB->CacheFlush();
  }

  function insert_items($DB,$data,$category){
        $sql=sprintf(
          "INSERT items (
            regist_date,
            name,
            type_id,
            catchcopy,
            detail,
            price_b_1,
            price_b_2,
            price_t_1,
            price_t_2,
            tantou,
            voice_s,
            voice_l,
            address,
            traffic,
            g_area_b,
            g_area_t,
            g_tubo_b,
            g_tubo_t,
            b_area_b,
            b_area_t,
            b_tubo_b,
            b_tubo_t,
            per_area_b,
            per_area_t,
            balcony_b,
            balcony_t,
            scale,
            layout,
            howold,
            build_date,
            land_usage,
            land_type,
            coverage,
            bulk_ratio,
            adm_cost,
            fix_cost,
            man_name,
            bikou,
            r_title_1,
            r_comment_1,
            r_title_2,
            r_comment_2,
            r_title_3,
            r_comment_3,
            is_new,
            is_near_sea,
            is_view_sea,
            is_top,
            visible,
            item_detail,
            category,
            is_sold,
            next_date
          ) VALUES (
            '%s',
            '%s',
            %d,
            '%s',
            '%s',
            %d,
            %d,
            %d,
            %d,
            %d,
            '%s',
            '%s',
            '%s',
            '%s',
            %01.2f,
            %01.2f,
            %01.2f,
            %01.2f,
            %01.2f,
            %01.2f,
            %01.2f,
            %01.2f,
            %01.2f,
            %01.2f,
            %01.2f,
            %01.2f,
            '%s',
            '%s',
            '%s',
            '%s',
            '%s',
            '%s',
            %d,
            %d,
            %d,
            %d,
            '%s',
            '%s',
            '%s',
            '%s',
            '%s',
            '%s',
            '%s',
            '%s',
            %d,
            %d,
            %d,
            %d,
            %d,
            '%s',
            %d,
            %d,
            '%s'
          )",
          mysql_escape_string(date("Y-m-d")),
          mysql_escape_string($data["name"]),
          $data["type_id"],
          mysql_escape_string($data["catchcopy"]),
          mysql_escape_string($data["detail"]),
          $data["price_b_1"],
          $data["price_b_2"],
          $data["price_t_1"],
          $data["price_t_2"],
          $data["tantou"],
          mysql_escape_string($data["voice_s"]),
          mysql_escape_string($data["voice_l"]),
          mysql_escape_string($data["address"]),
          mysql_escape_string($data["traffic"]),
          $data["g_area_b"],
          $data["g_area_t"],
          $data["g_tubo_b"],
          $data["g_tubo_t"],
          $data["b_area_b"],
          $data["b_area_t"],
          $data["b_tubo_b"],
          $data["b_tubo_t"],
          $data["per_area_b"],
          $data["per_area_t"],
          $data["balcony_b"],
          $data["balcony_t"],
          mysql_escape_string($data["scale"]),
          mysql_escape_string($data["layout"]),
          mysql_escape_string($data["howold"]),
          mysql_escape_string($data["build_date"]),
          mysql_escape_string($data["land_usage"]),
          mysql_escape_string($data["land_type"]),
          $data["coverage"],
          $data["bulk_ratio"],
          $data["adm_cost"],
          $data["fix_cost"],
          mysql_escape_string($data["man_name"]),
          mysql_escape_string($data["bikou"]),
          mysql_escape_string($data["r_title_1"]),
          mysql_escape_string($data["r_comment_1"]),
          mysql_escape_string($data["r_title_2"]),
          mysql_escape_string($data["r_comment_2"]),
          mysql_escape_string($data["r_title_3"]),
          mysql_escape_string($data["r_comment_3"]),
          $data["is_new"],
          $data["is_near_sea"],
          $data["is_view_sea"],
          $data["is_top"],
          $data["visible"],
          mysql_escape_string($data["item_detail"]),
          $category,
          $data["is_sold"],
          sprintf(
            "%04d-%02d-%02d",
            $data["next_year"],
            $data["next_month"],
            $data["next_day"]
          )
        );
        $DB->execute($sql) or die("cannot insert".nl2br($sql));

        $id=$DB->Insert_ID();
        
        if($category==0){
          if($data["type_id"]==1){
            $sql=sprintf(
              "INSERT into item_land(item_id)VALUES(%d)",
              $id
            );
            $DB->Execute($sql);
            $item_number="0".sprintf("%03d",$DB->Insert_ID());
          }elseif($data["type_id"]==2){
            $sql=sprintf(
              "INSERT into item_house(item_id)VALUES(%d)",
              $id
            );
            $DB->Execute($sql);
            $item_number="1".sprintf("%03d",$DB->Insert_ID());
          }elseif($data["type_id"]==3){
            $sql=sprintf(
              "INSERT into item_mansion(item_id)VALUES(%d)",
              $id
            );
            $DB->Execute($sql);
            $item_number="2".sprintf("%03d",$DB->Insert_ID());
          }
        }elseif($category==1){
          $sql=sprintf(
            "INSERT into recommend_item(item_id)VALUES(%d)",
            $id
          );
          $DB->Execute($sql);
          $item_number="3".sprintf("%03d",$DB->Insert_ID());
        }

        $sql=sprintf(
          "UPDATE items
          SET
            item_number='%s'
          WHERE
            id=%d",
          mysql_escape_string($item_number),
          $id
        );
        $DB->execute($sql);

        $DB->CacheFlush();
        
        return $id;
  }
  
  function get_item_data($DB,$id){
    $sql=sprintf(
      "SELECT *
      FROM
        items
      WHERE
        id=%d",
      $id
    );
    return $DB->GetRow($sql);
  }
  
}
?>